version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: docker/dev/app.dockerfile
      args:
        - USER
        - GID
        - USERID
        - OS
    environment:
      - "TZ=Europe/Rome"
    container_name: ${APP_NAME}_app
    volumes:
      - ./src:/var/www
    networks:
      - default

  web:
    build:
      context: ./
      dockerfile: docker/dev/web.dockerfile
    container_name: ${APP_NAME}_web
    environment:
      - "TZ=Europe/Rome"
    volumes:
      - ./src:/var/www
    ports:
      - ${HTTP_FORWARD_PORT}:80
    networks:
      - default

  database:
    image: mariadb
    container_name: ${APP_NAME}_db
    environment:
      - "TZ=Europe/Rome"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_FORWARD_PORT}:3306
    networks:
      - default

  redis:
    image: "redis:3.2"
    command: "redis-server --appendonly yes"
    container_name: ${APP_NAME}_redis
    environment:
      - "TZ=Europe/Rome"
    volumes:
      - "redis_data:/data"
    networks:
      - default

  scheduler:
    image: mcuadros/ofelia:latest
    container_name: ${APP_NAME}_scheduler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/dev/scheduler.conf:/etc/ofelia/config.ini
    depends_on:
      - app

volumes:
  mysql-data:
  redis_data:
networks:
  default:
    driver: bridge
