version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: docker/app.dockerfile
      args:
        - USER
        - GID
        - USERID
        - OS
    environment:
      - TZ=Europe/Rome
    container_name: ${APP_NAME}_app
    volumes:
      - ./:/var/www
    networks:
      - default

  supervisor:
    build:
      context: ./
      dockerfile: docker/supervisor.dockerfile
    container_name: ${APP_NAME}_supervisor
    environment:
      - TZ=Europe/Rome
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    container_name: ${APP_NAME}_web
    environment:
      - TZ=Europe/Rome
    volumes:
      - ./:/var/www
    ports:
      - ${HTTP_FORWARD_PORT}:80
      - ${HTTPS_FORWARD_PORT}:443
    networks:
      - default

  mysql:
    image: mariadb
    container_name: ${APP_NAME}_db
    environment:
      - TZ=Europe/Rome
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_FORWARD_PORT}:3306
    networks:
      - default

  redis:
    image: "redis:3.2"
    command: "redis-server --appendonly yes"
    container_name: ${APP_NAME}_redis
    environment:
      - TZ=Europe/Rome
    volumes:
      - "redis_data:/data"
    networks:
      - default

  scheduler:
    image: mcuadros/ofelia:latest
    container_name: ${APP_NAME}_scheduler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scheduler/config.ini:/etc/ofelia/config.ini
    depends_on:
      - app

volumes:
  mysql-data:
  redis_data:
networks:
  default:
    driver: bridge
